config/routes.rb
Rails.application.routes.draw do
  
  
 root to: 'pages#home'
 devise_for :users
  get 'pages/contact'
  resources :patients
  
  get 'doctor/index'
  get 'doctor/show'
  resources :appointments
  get 'appointments/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/appointment.rb
class Appointment < ApplicationRecord
	 attr_accessor :appointments_attributes
	belongs_to :patient
	belongs_to :doctor
	accepts_nested_attributes_for :doctor

	
end 

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create]
  after_action :set_taken,  only: [:create]


  # GET /appointments
  # GET /appointments.json
  def index
    
   
    #@appointments = Appointment.all
     @appointments = Appointment.order(:created_at).page(params[:page]).per(2)
    
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show

  end

  # GET /appointments/new
  def new

    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    
    @appointment = Appointment.new (appointment_params)


    respond_to do |format|
      if @appointment.save
       # @custcity = Custcity.create({cityname: params[:customer][:cityname], cust_id: @customer.id})
      
        #@patient = Patient.create( patient_id: :@appointments.patient.id, name: 81831000, illness: :@appointments.illness, doctor_id: :@appointments.doctor.id)
        #Country.create( name: 'Germany', population: 81831000 )
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    def set_taken
    
     @appointment.taken = 'Y'
   end
   private
  def add_appointment
    #a=Appointment.create!(:doctor_id, :time_slot, :appt_date, :taken =>'Y')
    @appointment = Appointment.new(app_params)
        
    
   @appointment.save
       redirect_to patients_path
      
 end

   

    # Only allow a list of trusted parameters through.
    def appointment_params
      params.require(:appointment).permit(:doctor_id, :time_slot, :appt_date, :patient_id, :taken)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= form_with(model: appointment, local: true) do |form| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
   

  <div class="field">
    <%= form.label :Doctor %>
 
     <%= form.collection_select :doctor_id, Doctor.all, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :Time_Slot %>
    <%= form.time_select :time_slot %>
  </div>

  <div class="field">
    <%= form.label :Book_On %>
    <%= form.date_select :appt_date %>
    <%= form.hidden_field :id, value: current_user.id%>
  </div>
   
    <% end %>

  <div class="field">
    <% if current_user %>
        User ID:<%= current_user.id %>
        User Name: <%= current_user.name %>
        
   
   <%= form.hidden_field :patient_id, value: current_user.id%>
   
  </div>

  

  <div class="actions">
    <%= form.submit :'Book now'%>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h3>Editing Appointment</h3>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<% content_for :appindex do %>

<style>
table {
  border-collapse: collapse;
  width: 75%;
  margin: 75px
}
th, td {
  text-align: left;
  padding: 8px;
}


tr:nth-child(even) {background-color: lightblue;}
</style>

<!--<p id="notice"><%= notice %></p>-->

<h3>Doctor's Schedule</h3>
<%=paginate @appointments %>

<table>
  <thead>
    <tr>
      <th>Patient</th>
      <th>Doctor</th>
      <th>Speciality</th>
       <th>Date</th>
      <th>Time</th>
      
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        
      
       <td><%= appointment.patient.name %></td>
       <td><%= appointment.doctor.name%></td>
       <td><%= appointment.doctor.speciality %></td>
       <td><%= appointment.patient.appdate.strftime("%d/%m/%Y")%></td>
        <td><%= appointment.patient.apptime.strftime("%I:%M %p") %></td>
       
       <td><%= link_to 'Reschedule', edit_patient_path(appointment.patient.id) %></td>
        <td><%= link_to 'Cancel', appointment, method: :delete, data: { confirm: 'Do you want to cancel your appointment?' } %></td>
        
       
       
       
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%end%>

app/views/appointments/new.html.erb
<% content_for :newbooking do %>


<h3> New Appointment</h3>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Back', appointments_path %>

<%end%>

app/views/appointments/show.html.erb
<% content_for :showappointments do %>

	
<p id="notice"><%= notice %></p>

<p>
  <strong>Doctor:</strong>
  <%= @appointment.doctor.name%>
</p>

<p>
  <strong>Time slot:</strong>
  <%= @appointment.time_slot %>
</p>

<p>
  <strong>Appt date:</strong>
  <%= @appointment.appt_date %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @appointment.patient.name%>
</p>


<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>

<%end%>